In [1]:
import tensorflow_datasets as tfds
import tensorflow as tf

In [2]:
file = open("./en_cn/cmn.txt",'r', encoding='UTF-8') 
all_lines = file.readlines()
enlish = []
chines = []
for line in all_lines:
    enlish.append(line.strip().split()[:-11])
    chines.append(line.strip().split()[-11])

In [3]:
enl = []
for i in enlish:
    print(' '.join(i).replace('.','').replace('!','').replace('?',''))
    enl.append(' '.join(i).replace('.','').replace('!','').replace('?',''))
chi = []
for i in chines:
    print(''.join(i).replace('。','').replace('！','').replace('？',''))
    chi.append(''.join(i).replace('。','').replace('！','').replace('？',''))

Hi
Hi
Run
Wait
Wait
Hello
I won
Oh no
Cheers
Got it
He ran
Hop in
I quit
I'm OK
I'm up
Listen
No way
No way
Really
Try it
We try
Why me
Ask Tom
Awesome
Be calm
Be fair
Be kind
Be nice
Be nice
Call me
Call us
Come in
Get Tom
Get out
Get out
Go away
Go away
Go away
Go home
Goodbye
Goodbye
Hang on
Hang on
Hang on
He came
He runs
Help me
Help us
Hit Tom
Hold on
Hug Tom
Hug Tom
I agree
I'm ill
I'm old
I'm wet
It's OK
It's me
Join us
Keep it
Kiss me
Perfect
See you
Shut up
Skip it
Take it
Wake up
Wash up
We know
Welcome
Who won
Why not
You run
You win
Back off
Be still
Beats me
Cuff him
Drive on
Get away
Get away
Get down
Get lost
Get lost
Get lost
Get real
Good job
Good job
Grab Tom
Grab him
Have fun
He tries
How cute
Humor me
Hurry up
Hurry up
Hurry up
I did it
I forgot
I resign
I'll pay
I'm busy
I'm cold
I'm fine
I'm full
I'm lost
I'm sick
I'm sick
I'm tall
Leave me
Let's go
Let's go
Let's go
Look out
Say what
She runs
Stand up
Terrific
They won
Tom died
Tom lied
Tom lost
Tom quit
Tom swa

She worked hard
She's my sister
She's on a diet
She's on a diet
Spring has come
That dog is big
That feels good
That isn't fair
That smells bad
That's a pencil
That's my money
That's not fair
That's terrible
That's too easy
That's very big
The boy is kind
The dog is dead
The leaves fell
The light is on
The sea is blue
The taxi's here
There's no rush
There's no salt
They all did it
They are melons
They sell candy
They're talking
This book's new
This is my bike
This is my book
This is my wife
This is the end
This is too big
This is typical
This isn't good
This isn't love
This isn't salt
Time for dinner
Tom also talked
Tom did nothing
Tom disappeared
Tom fell asleep
Tom felt hungry
Tom has no time
Tom hugged Mary
Tom is a racist
Tom is ecstatic
Tom is escaping
Tom is hammered
Tom is laughing
Tom is not dumb
Tom is out cold
Tom is swimming
Tom is thrilled
Tom isn't lying
Tom isn't wrong
Tom looked well
Tom seems tough
Tom stayed home
Tom was a nurse
Tom was at home
Tom was bullied
Tom was 

You're quite right
You're still green
You're still young
You're such a jerk
You're turning red
"Trust me," he said
A whale is a mammal
Am I a good teacher
America is very big
Answer my questions
Answer the question
Are those new shoes
Are you guys crying
Are you off tonight
But I don't want to
Can I have some tea
Can you drive a car
Can you really swim
Christmas is coming
Come again any time
Could I try this on
Could you sign here
Destroy this temple
Do you drink coffee
Do you go to church
Do you have a child
Do you have a cough
Do you have a fever
Do you have a knife
Do you know my name
Do you like English
Do you like oranges
Do you like spinach
Do you speak French
Do you want to know
Does Tom have a job
Don't drop this cup
Don't let Tom leave
Don't listen to her
Don't stand near me
Don't you feel cold
Don't you know that
Dry wood burns well
Enjoy your holidays
Every minute counts
Everybody knows her
Everybody thinks so
Everyone's laughing
Everything is ready
Everything seems OK
Every

Who did you talk with
Who do you think I am
Who planted this tree
Who told you the news
Who wrote these poems
Who wrote these poems
Who's your girlfriend
Whose bicycle is this
Whose is this bicycle
Why are you asking me
Why can't we talk now
Why did you come here
Why did you marry Tom
Why don't you go home
Why don't you grow up
Why is change so hard
Why should I hire Tom
Will he come tomorrow
Will it rain tomorrow
Will you stay at home
Would you like a tour
Write everything down
Write me sometime, OK
Write your goals down
You are a good person
You are a good person
You deserve the prize
You didn't protect me
You don't have to eat
You must do your best
You must stop smoking
You need to get ready
You need to seek help
You reap what you sow
You reap what you sow
You seem very nervous
You should make notes
You weren't here then
You'll get used to it
You'll never be alone
You'll never be alone
You're a mean old man
You're frightening me
You're in big trouble
You're really useless
You've got

Wash your face and hands
We accept your challenge
We bought a pound of tea
We buy eggs by the dozen
We didn't get an apology
We didn't start the fire
We do what we want to do
We expect a lot from him
We go to school to study
We go to the same school
We had some chicken soup
We have the same problem
We import tea from India
We just want to find Tom
We know what we're doing
We must follow the rules
We must make a new start
We need some more coffee
We need to get some help
We ordered too much food
We ought to obey the law
We postponed the meeting
We raced toward the fire
We should run some tests
We want you to marry Tom
We'll be late for dinner
We'll come back tomorrow
We're just like brothers
We're on the third floor
We're preparing to do so
We've got plenty of time
We've run short of money
Welcome to your new home
What are they doing here
What are you doing there
What are you girls doing
What are you laughing at
What are you laughing at
What are you laughing at
What are you reading now


My French isn't good enough
My aunt made me a new skirt
My aunt made me a new skirt
My aunt made me a new skirt
My aunt made me a new skirt
My birthday falls on Sunday
My blood type is A positive
My car isn't red It's blue 我的汽車不是紅色的,
My car's not red It's blue 我的汽車不是紅色的,
My father cannot lift it up
My father has five siblings
My father is in good health
My father made me what I am
My father runs a restaurant
My grades are above average
My grandson is still a baby
My left eyelid is twitching
My mother left me a message
My mother made me a sweater
My mother never punishes me
My uncle gave his car to me
My vacation went by quickly
Nature is full of mysteries
Next time I'll come earlier
No one answered my question
No one here will betray you
No one supported his motion
No one will bother you here
Nobody else offered to help
Nobody had ever heard of it
Nobody had ever heard of it
Nobody wants you to do that
Now shake hands and make up
Now who's going to help you
Ogai is his favorite author


Have you cleaned your room yet
Have you ever climbed Mt Yari
Have you ever dreamed about me
Have you ever seen Tokyo Tower
Have you ever shaved your legs
Have you found your ticket yet
Have you seen all these movies
Have you seen all these movies
Have you turned in your report
Have you washed your hands yet
Have you worked the puzzle out
He always keeps his room clean
He always takes sides with her
He always takes sides with her
He applied for the scholarship
He arrived after the bell rang
He asked her to call him later
He asked me whether I was busy
He asked me why I was laughing
He behaved as if he were crazy
He bought his daughter a dress
He broke the window on purpose
He came home three hours later
He came to Japan two years ago
He came to my office yesterday
He can do it better than I can
He can scarcely write his name
He carried six boxes at a time
He caught them stealing apples
He cheated on the biology exam
He comes here almost every day
He comes here every three days
He denied

Tom watches too much television
Tom's comment was inappropriate
Tom's eyesight is deteriorating
Tom's good, but not good enough
Tom, Mary and John are all here
Turn the knob and open the door
Wait till the light turns green
War may break out at any moment
Watch him and do the same thing
We are anxious about her safety
We are leaving Japan next month
We ate sandwiches for breakfast
We can hear the ocean from here
We can't get close to the enemy
We can't stay in here very long
We caught some large fish there
We climbed Mt Fuji last summer
We discussed the plan yesterday
We divided the money between us
We don't get many visitors here
We don't want anything from you
We enjoyed swimming in the lake
We gave blood to help the child
We give a 10% discount for cash
We go fishing from time to time
We had an early lunch at school
We had an earthquake last night
We have many rainy days in June
We have no reason to be ashamed
We have plenty of time to spare
We hope you will enjoy the show
We know t

Do you have a lot of time to relax
Do you have any Japanese magazines
Do you have any plans for Saturday
Do you have something to say to me
Do you have these shoes in my size
Do you know the boy in the picture
Do you know where your father went
Do you need help carrying anything
Do you remember where we first met
Do you still want to give me a hug
Do you want to eat noodles or rice
Doing that is a waste of your time
Don't forget to turn the light off
Don't let anyone press this button
Don't let him play with your phone
Don't make noise when you eat soup
Don't put your elbows on the table
Drunk driving is a serious problem
Dutch is closely related to German
Edison invented many useful things
Everything comes to those who wait
Father always says, "Do your best"
Generally, Japanese people are shy
Germany was once allied with Italy
Give the book to whomever wants it
Give this book to whoever wants it
Good morning It's time to wake up
Have you already rung the doorbell
Have you been busy si

You wouldn't believe me if I told you
You'll soon get used to Japanese food
Zimbabwe was once a colony of Britain
"How old are you" "Sixteen years old"
"I feel like playing cards" "So do I"
A day without laughter is a day wasted
A little learning is a dangerous thing
A man suddenly appeared in the doorway
A wounded whale washed up on the beach
Advertisements urge us to buy luxuries
All I really want to do is talk to Tom
All the flowers in the garden withered
An eye for an eye, a tooth for a tooth
An eye for an eye, a tooth for a tooth
An old man broke into our conversation
Are you still living with your parents
Are you sure that you want to go there
As far as I know, he did nothing wrong
As far as I know, she is still missing
Boys, as a rule, are taller than girls
Can I use your dictionary for a minute
Can you please give me something to do
Can you put up with the way he behaves
Class doesn't begin until eight-thirty
Coal and natural gas are natural fuels
Could you wrap this separately

Pilots communicate with the airport by radio
Please remind me to mail the report tomorrow
Please translate this sentence into Japanese
Refugees poured in from all over the country
She asked me whether I liked the plan or not
She did not visit me on Sunday but on Monday
She got over the shock of her father's death
She has changed greatly since I last saw her
She has to take a remedial course in English
She is going to wash the bike this afternoon
She rested her head on her mother's shoulder
She's not a regular employee of this company
Some abstract art is difficult to understand
Some diseases are caused by a defective gene
Some of them are healthy, but others are not
Take off your hat when you enter a classroom
Take off your hat when you enter a classroom
The Colombian government demanded more money
The cat arched its back and stretched itself
The charge for a front row seat is 5 dollars
The fire broke out after the staff went home
The flowers in the garden need to be watered
The inform

静静的，别动
我一无所知
把他铐上
往前开
走開
滾
趴下
滾
滚
滚
醒醒吧
做得好
干的好
抓住汤姆
抓住他
玩得開心
他来试试
多可爱啊
你就随了我的意吧
趕快!
快点
快点
我做到了
我忘了
我放弃
我來付錢
我很忙
我冷
我很好
我吃飽了
我迷失了
我生病了
我病了
我个子高
让我一个人呆会儿
走吧
我們開始吧
我們走吧!
当心
啥
她跑
起立
很棒
他们赢了
汤姆去世了
汤姆说谎了
汤姆输了
汤姆不干了
汤姆游泳了
Tom游泳
相信我
努力
试试吧
试试这个
谁死了
鳥類飛行
打电话回家
冷静点
抓住他
回家吧
冷静点
現在就做
狗会叫
别哭
对不起
好棒
很棒
来感受一下这个
请跟我来
请跟着我们
祝你好运
晚安
抓住那个
抓住这个

他很懒
停火
太可怕了
多怪啊
我冷
我迷失了
我沒事
我生病了
我个子高
我拍手
我了解你
我放弃
我希望如此
我笑了
我向你保证
我看見湯姆了
我害羞
我要游泳
我是个男人
我覺得很無聊
我是第一
我是對的
对不起
我很抱歉
我還年輕
遠嗎
下雪了
3点半了
天很冷
它是食物
它是免費的
很晚了
這是真的
留着吧
殺了他們
让我进去
躺着不动
回头看
腾一下地方
當然!
當然
当然了
噢拜托了
开火
念这个
参见上文
她哭了
她试过了
她在行走
耐心等着
慢一點
保持冷靜
趴着
住手
照顾好自己
照顾好自己
谢谢
他们离开了
汤姆睡了
Tom游泳
湯姆累了
汤姆挥手了
湯姆要走
向左转
在这等着
当心
做得好
干的好
爱谁谁
她是谁
很棒
蠢货
你身上发臭了
请上船
我錯了嗎
要守时
耐心等着
鳥兒歌唱
我可以幫忙嗎?
进来
必须的
别动
不要动
不要等待
把它填滿
跟著他走
回家吧
去洗洗吧
上帝存在
晚安
他让步了.

他很懒
他很凶
他很穷
他高
你好，汤姆
嘿，放松点
多可爱啊
工作怎么样
赶快回家
我是个男人
我个头矮
我会做饭
我會游泳
我不能走
我在這裡吃
我嫉妒她
我羡慕他
我恨你
我认识汤姆
我認識他
我喜欢茶
我喜歡你
我喜欢你
我愛她
我爱您
我想念他
我想念你
我需要你
我想是這樣的
我使用这个
我會做的
我是個英雄
我是个骗子
我是谦虚的
我单身
我單身
我困了
我好胖哦
我三十歲
别理汤姆
他长得高吗
那是愛嗎
真是太好了
是晚上了
放松点吧
继续吧
坚持
坚持
保持安静
保持安静
让他进

你得走了
你知道得太多了
你犯了个错误
我被你逗乐了
你讓我快樂
这里可以停车
您可以拿着这个.
您要赶快些
你必須離開
你說太多了
你不會需要它
你工作太努力了
你真是警惕
你很聪明
你做了很多
任何人都可以做到
你是单身吗
你今天忙吗
你在生汤姆的气吗
你还冷吗
你睜著眼嗎
你不渴嗎
当心它
早饭准备好了
我能看那個嗎
我能看看這個嗎
我可以用你的筆嗎
我們現在能回去嗎
可以原谅我吗
车子很贵
请跟我来
跟我們一起來吧
进来，门开着
来，再试试看
他們從前住這嗎
你把它们带来了么
你检查这个了吗
是你杀了汤姆吗
你告发我了吗
你喜欢苹果吗
你喜歡坐飛機嗎
你們喜歡學校嗎
您喜歡學校嗎?
你踢足球嗎?
你的牙齦流血嗎
很痛嗎?
好吃嗎
別被嚇壞了
别让他失望
不要错过公车
别胡说
你不这么认为吗
每个人都做了那事
所有人都是活着的
人固有一死
大家都喜歡湯姆
所有人都喝醉了
每個人都高興
任何事情都是重要
一切就绪
內用還是外帶?
把那个号码给我
给我报告
给我你的手机
戴上你的安全帽
把遥控器递给我
你們吃飯了嗎
他及時趕到
他准时来了
他問候了你
他替我叫了一部計程車
他會開車
他不能买车
他真的說得很好
他帮我打到一辆出租车
他給了他一本書
他下了公車
他沒有孩子
他還沒來
他給自己投了保險
他是個糟糕的司機
他上电台了
他是这么的无情
他殺死了那個人
他在我面前撒谎.
他愛旅行
他從來沒說過那個
他玩得很好
他弹得很好
他舉起他的手
他六点回来了
他好像病了
他開了先河
他说话太快了
他仍然爱着她
他偷了她的手表
他休了一周的假
他要愛
他獨自在那裡
他骑自行车去的
他騎腳踏車去
他會等你
他是个好人
他是個好人
他有点苍白
他是个吸毒男
他已经是个男人了
他在靠近
他心情不好
他是我新交的朋友
她的頭髮長回來了
她的皮膚光滑
她的襪子是灰色的
这是我的行李
馬是動物
他怎麼找到我們的
這是怎麼運行的
天氣怎樣
你家里人都还好吗
你感觉如何
我接受了报价
我完全同意
我幾乎從不說謊
我是个新生
我是獨生子
我来自葡萄牙
我不是學生
我不是個老師
我六英尺高
我吃了炸薯條
我每天洗一次澡
我燒了紙
我甚麼都能吃
我能幫你
我可以等你
我没法相信
我不可以喝牛奶
我不能喝牛奶
我睡不好
我拍手
我沒有那個意思
我沒告訴他們
我不想要這個
我不怕死
我沒有汽車


這是什麼語言
为什么她要做这种事情呢
你们什么时候开始营业
我的房间号是多少
你到底怎么回事啊
你到底怎麼回事啊
你是什麼時候來的
这什么时候能准备好
他們何時抵達?
你什麼時候有空?
浴室在哪里
你的東西在哪裡?
你們的東西在哪裡
您的東西在哪裡
你的東西在哪裡
你们这些家伙去哪儿了
你现在住在哪里
你现在在哪里工作
我的报纸在哪里
洗手間在哪裡
電梯在哪裡
錯在哪裡
你和谁说话呢
你把我当什么啦
谁种了这棵树
誰告訴了你這個消息
这是谁写的诗
这些诗的作者是谁
你女朋友是谁
这辆自行车是谁的
这辆自行车是谁的
你為什麼問我
为什么我们现在不能讲
你為什麼來這裡
你為甚麼跟湯姆結婚
你为什么不回家呢
你为什么长不大呢
為什麼改變那麼難
为什么我要雇佣Tom
他明天会来吗
明天会下雨吗
你会待在家吗
你想去旅游嗎
把所有東西寫下來
有时间给我写信，好吗
把你的目標寫下來
你是一個好人
您是一個好人
你應該得到這個獎金
你没有保护我
你不必吃
你必须做到最好
你必须停止吸烟
你需要做好准备
你需要尋求協助
种瓜得瓜，种豆得豆
種什麼因得什麼果
你看起来很紧张
你应该做笔记
你那時不在這裡
你会习惯的
你们永远不会一个人的
你永远不会一个人的
你这个吝啬的老头
你在嚇我
你们有大麻烦了
你真沒用
你必須醒醒
你犯了个错误
你的猫抓伤我了
零在一前面
我有一个好主意
一块岩石从上面落下
海绵吸水
1000日元足够了
每条狗都活着
所有狗都活着
所有你能做的就是等待
他们都像这一样吗
他们都是一样的吗
你怕虫子吗
你怕狗吗
你在生汤姆的气吗
你跟人約會過嗎
你現在有空嗎
你在嘲笑我吗
你在跟我说话吗
你是在对我说吗
小心别摔倒了
迟做总比不做好
迟到总比不到好
你和我都是男人
把那本雜誌拿來給我
我能把我的车停在这儿吗
誰會相信你
我们能拯救这颗星球吗
我们能私下谈谈吗
你會記帳嗎?
快一点好吗
能請你離開嗎
你會彈鋼琴嗎
你可以閉嘴嗎
您会使用计算机吗
我们做不成吗
猫不吃香蕉
請關上門
請關門
过来和我跳舞啊!
什么时候想来就过来吧
把帳單給我好嗎
你能来这里吗
你可以轉小聲一點嗎?
爸爸给我买了一个照相机
死人不會告密
他們有買果汁嗎
你聽到了點擊聲嗎
你看到他出去了嗎
你看了比賽嗎
我们有足够的食物吗
您经常来这儿吗
您喝绿茶吗
你們認識嗎
你知道答案嗎?
你知道是

由你來決定
請相信我的話
记好了这教训
讓他彈你的吉他
讓我看一下你的票
讓我跟湯姆說明
讓我給你說明
讓我看看它
讓我給你沏茶
讓我思考一下
改天再說吧
再找時間吧
讓我們再聚在一起!
我们别自骗自了
讓我們休息一會兒
小心扒手
看我为你做了什么
許多朋友為他送行
瑪麗必須去上學
我可以問一些問題嗎?
我可以问你个问题吗
我可以去洗手間嗎
我可以去洗手間嗎
我們能私下見見嗎
媽媽有一個咖啡廳
浅间山现在是寂静的
我的阿姨給了我一台攝影機
我姑姑給了我一張唱片專輯
我姑姑給了我一本相簿
我姑姑給了我一本集郵冊
我的血压很低
我父親開車去上班
我爸爸给我了游戏
我父親在他的房間裡
我门牙突出
我的房子又舊又難看
我丈夫没在城里
我的工作是洗碗
我的工作是洗盤子
我的工作是洗碗
我的工作是洗盤子
我母亲十分生气
我的房間面向花園
我的肩膀很痠
我们队总是输
我们队从来就没赢过
我叔叔給了我他的車
我的表被偷了
沒人應該擔心
没人试图帮汤姆
什么都没按他的路子走
沒有多少改變
這些狗中的其中一隻是活的
我家宝宝还不会说话
请把盐递给我
请给我盐
請把酒遞給我
人們應該在跳舞
請選擇一個人
請不要用我的名字
请帮我找一下我的钱包
請給我送一塊毯子
请敲门
請穿上你的鞋子
請穿上你的鞋子
請說大聲一點兒
請說更大聲一點
請說話大聲一點
请您摘下您的帽子
请告诉我汤姆很好
請告訴我你的名字
請打開收音機
请打开收音机
请将收音机打开
請先等他
請澆花
他對政治沒有興趣
骄傲是失败的先行者
骄傲使人落后
把槍放在桌子上
盡可能地多閱讀書籍
她也喜欢巧克力
她和我是同學
她的左手被燙到了
她打了很多次電話給我
她决定和他结婚
她不喜歡她的丈夫
她與丈夫離婚
她从梯子上摔了下来
她上夜校
她不得不待在这儿
她看到了更好的明天
她是個很棒的女人
她是个倔强的女孩
她现在正在工作
她是他的一切
她錢不夠
她派他去工作了
她匆忙地離開了這裡
她馬上離開了這裡
她也喜欢巧克力
她看起来像老师
她也喜欢巧克力
她做了一件好看的衣服給我
她為我做了這個娃娃
她喜欢啤酒胜过葡萄酒
她唱得比他好
她寄這本書給我
她把照片给他看
她邊走邊談
她昨天去那裡
她是Tom的姐姐
她沒有瑪麗年紀大
我该取消通话吗?
有人推我到裡面
春天快來了
退到繩子後面
打的去旅馆吧
你爱拿多少就拿多少
让她中午过来
十年

她对谁都很和蔼可亲
她精通法語
她是个合格的护士
她坐在長椅上
她正在澆花
她養一隻鸚鵡作為寵物
她亲吻他的脸颊
她在他的脸颊上吻了一下
她把工作弄得一團糟
她工作做得亂七八糟
她做了一套新衣服給他
她取笑了她的丈夫
她继续工作
她盡可能地快跑
她一整天都沉默不语
她骑摩托车的技术不错
她說她以前很快樂
她说了她很幸福
好像她病了
她在他的背上戳了一下
她感謝我們的幫助
她企圖自殺
她很想要一条新的连衣裙
她被哈佛錄取了
她被哈佛大學錄取了
她幾乎被車撞到
她忙於家務
她握着一把伞
她穿了一件蓝色大衣
她五點前不會回來
她五點鐘才會回來
她穿了一件宽松的长外套
唱歌是她的强项
六除以二得三
吸烟有害健康
这里不允许抽烟
那么，这次发生了什么
足球是我最喜欢的运动
有些食物令人口渴
有些人不知道那件事
某人把我的杯形蛋糕吃完了
說英語是不容易的
請脫下你的襪子
老师也会犯错
泪水沿着我的面颊流了下来
告訴湯姆一切都好
十間房屋被燒毀了
网球是我最喜欢的运动
谢谢你的耐心
谢谢你的解释
那件事情使他一舉成名
那幢房子看起来被遗弃了
那頓飯簡直好極了
那是個美好的瞬間
那不难，是吧
这就是他所说的
那不重要，不是么
日本人有黑色的眼睛
酸性腐蚀了金属
回答偏了
观众人数庞大
群鸟南翔
這個男孩把他的手弄髒了
男孩學會了閱讀
公交车迟到了
这顶帽子对我来说太小了
小丑做了个鬼脸
期限近了
設計本身有問題
医生可能说过
這隻狗的一隻眼睛瞎了
那狗一只眼是瞎的
為了正當目的可以不擇手段
這魚吃著像三文魚
货物毫无损坏地到达了
长胡子的是汤姆
灯突然灭了
損失是無法估計的
这药创造了奇迹
這隻老鼠跑進洞裡
社區是安靜的
這位老人下了公車
壓力很巨大
这个价格不合理
这份报告完全错误
房間裡家具齊全
房里有股烟味
房里闻起来有股烟味
這房間是由湯姆清掃的
经过证实，谣言是真的
天空完全变黑了
明天有足球比賽
商店周一关门
條紋是水平的
电视机坏了
火车应当准点到
今晚天公作美
桌上有個杯子
这没什么好担心的
金窩銀窩不如自己的狗窩
明天會下雪喔
這些洋裝太大
這些橘子很酸
他们都哈哈大笑起来
他們總是抱怨
他们不怕死
他們決定結婚了
他們禮拜天上教堂
他們休息了一會兒
他们一个接着一个地离开了
他們讓我獨自去了那裡
他們要我們整夜工作
他們甚麼也不會告訴我們
他们不会再见面了
这篇

您是老师，还是学生
你在做什麼特別的事嗎
你明天要來嗎
你对政治感兴趣吗
你是真的很樂意幫忙嗎?
你不要跟我一起走嗎
对于我，我不反对
一开始，我以为我病了
小心不要感冒了
蜜蜂螫人可以是非常痛苦的
啤酒瓶是玻璃做的
貝多芬是一個偉大的音樂家
我的两个姐妹都结婚了
我總想不出什麼好點子
請把報紙拿來給我
請幫我把今天的報紙帶來
回来的路上买点牛奶
今晚给汤姆和玛丽打电话
我可以使用我的醫療保險嗎
有人能发这个词的音吗
你能猜到我有什么吗
您能教我下国际象棋吗
你可以分出那對雙胞胎中誰是誰嗎?
你能辨别小麦和大麦吗
你不能打一點折嗎
你不能待久一點嗎
聖誕節是一個特別的節日
出去的时候把门关上
最晚十點前來這裡
比較你和湯姆的答案
Cookie的母親死於癌症
我们能去别的地方谈谈吗
你可以幫我提我的袋子嗎?
你能在放學後幫助我們嗎
你可以載我回家嗎?
你可以幫我叫一輛計程車嗎?
你能給我看看這條領帶嗎
您能好好给我们照一张相吗
你能告訴我湯姆在哪裡嗎
乌云是下雨的征兆
我有告訴你我找到新工作了嗎
你昨天去上學了嗎
他們在加拿大說法語嗎
做你認為正確的事
你相信神存在嗎
你們要和我一起去嗎
你說不定知道他的名字
你有駕駛執照嗎
你有一个固定的男朋友吗
你有止咳藥嗎
你身上有錢嗎
您有新鮮草莓嗎
您会开车吗
你知道如何開車嗎
你知道她什麼時候會來嗎
你知道为什么它正在发生吗
你知道她為什麼這麼生氣嗎
你喜歡打排球嗎
你介意我開門嗎?
你提供任何全日遊嗎
你知道這是甚麼意思嗎
你为你的工作感到自豪吗
你以为我造钱啊
你認為湯姆玩得高興嗎
你認為湯姆滿意了嗎
你要這些書中的任何一本嗎
你想要什么喝的吗
你今晚想出去吃嗎
你想知道我看见什么了吗
您想知道为什么我要离开吗
你想再待下去嗎
有人想要更多的餡餅嗎
他知道你愛他嗎?
聽起來像是我戀愛了嗎
不要再上學遲到了
不要把這個錯誤歸咎於她
別抱怨了你必須去
不要把欲望和爱情混为一谈
不要忘了寄這封信
别忘了带个相机
不要忘記簽上你的名字
不要超速
别让汤姆躺在地板上
千万别理汤姆
不要插手我的私生活
不要在陽光下逗留太久
不要踩在碎玻璃上
不要把事情看得這麼嚴重
不要丟掉這本雜誌
别用机翻
不要擔心這樣的事情
你從不清掃你的房間嗎
你不喜歡我的黃圍巾嗎
司機應該繫安全帶
他們每個人都被授獎了
英語是一種日耳曼語
在澳洲的人說英語

请叫消防员
请尽快过来
请继续讲你的故事
請原諒我的魯莽
請先填寫這張表格
请你给我一杯水
請給我一杯水
請給我點東西吃
请看这本书
請幫我做我的家庭作業
进来之前请敲门
請讓我為你拍照
請你來之前打電話給我
带我向你家人问好
請給我們更多訊息
請先為他上菜
請讓我看看你受傷的手臂
請讓我看看你的集郵冊
請隨手關門
你想待多久就待多久
請告訴我應該做什麼
請告訴我下一步去哪裡
为将来做准备吧
油墨快没了
把書放在你找到的地方
电视代替了收音机
拼命地跑
跑步對你的健康有益
代我向你父親問好
明天图书馆见
明天图书馆见
废水经常污染海洋
莎士比亞的作品太難讀了
我彈鋼琴為她伴奏
她指責我說謊
她和我同班
她要求我們別吵她
晚飯後她變得昏昏欲睡
她買了兩磅的奶油
她故意把窗戶弄壞了
她能遊得比我遠
她急忙地清掃了她的房間
她不需要做那個工作
她不想涉入其中
她不再住在那裡了
她只吃蔬菜
她看完信了
她輕輕地推了門
她每天早上早起
她七點鐘到車站
她揮著手向他打招呼
她面帶大大的笑容向我招呼
她有一整籃的蘋果
她有一个儿子和两个女儿
她是个很坦率的人
她已經離開了辦公室
她已經死了十年了
她把我介紹給她父親
她总是尝试新事物
她擅長說英語
她擅長說英文
她在找她的車鑰匙
她現在八十一歲了
她比你大兩歲
她對你的母親很熟悉
她留了很多钱给她儿子
她非常像她的母亲
她特地來拜訪我
她又犯了同樣的錯誤了
她或许知道我们在这儿
她昨天一定已經做過了
她一定很用功讀書
她在花園裡種了玫瑰
她在鋼琴上彈了一首華爾滋舞曲
她早上打網球
她假裝生病了
她把乾淨的床單鋪在床上
她真的想減肥
她拒絕接受這筆錢
她為我們唱了一首日文歌
她上週去旅行了
她给客人看了她的宝宝
她把自己关在房里
她花了整個下午作飯
她整天待在房子裡
她撿起了一塊鵝卵石
她上私人鋼琴課
她教閱讀和寫作
她往往會上學遲到
她以为我是大夫
她告訴我她認識我的哥哥
她告訴我們道路被封閉了
她搭計程車去醫院了
她把信成碎片
她逐字地翻譯它
她周遊世界各地
她经常九点睡觉
她是个数学天才
她听到那个消息后惊呆了
她忙著做她的功課
她不是一個很好的鋼琴家
她對於我送的禮物感到很開心
她明年將滿十七歲
她写了一本关于鸟类的书
她會永遠愛她的丈夫
她对我来说是一个完全陌生的人
她是一個非常有趣的人
她不在是因为病了
她在无理取闹
她

這輛計程車載了兩名乘客
老師跟我們說了一個有趣的故事
小偷帶著錢逃跑了
這張票的有效期是三天
这张票三日有效
厕所冲水不正常
火车挤满了人
風從東方吹來
有許多瀕危物种
公园里有很多人
罐子裡有一些餅乾
一年有十二個月
桌子底下有一個籃子
這棟房子的周圍有籬笆
房里有个电视机
這個池塘裡的水很少
沒有剩下一滴水
這個玻璃杯裡沒有任何的牛奶
昨晚下大雨
去年下了很多雪
計劃突然改變
沒有重建的錢
那儿除了我，一个人都没有
几乎没剩下钱
沒有人在家
湖上有一些船
對街有一家旅館
我对此无能为力
正有什么奇怪的事情发生着
這些花有一種獨特的氣味
这些机器目前不运转
這些玩具適合女生
他們從巴西遠道而來
他们从巴西远道而来
他們不知道先做什麼
在英國開車要靠左行駛
他們在12點吃晚飯
他們不知道正在發生甚麼
他們要他作隊長
他們好好地利用他們的房間
他們在還很年輕的時候就結婚了
这里只卖女鞋
他们报告目击了事故
他們應該十點前到
他們在紐西蘭講英語
他們從我的果園偷了蘋果
他們想知道湯姆在哪
他們全部穿制服了
事情要失控了
這張書桌比那張好
這個家庭作業對我來說很困難
这是我们之间的秘密
這是鎮上最便宜的商店
這本舊書值5萬日元
這張沙發占了太多空間
z这个理论很有争议
這班火車九點鐘發車
這班火車每站都停
这项工作未必容易
那种鞋子用来登山是不行的
沒有空氣生活是不可能的
简而言之，我不同意
汤姆和玛丽有很多共同点
汤姆问我是否喜欢巧克力
湯姆盡量避開瑪麗
湯姆可以比我做得好很多
汤姆打棒球打的非常好
汤姆常来这里
湯姆昨晚沒吃晚餐
汤姆似乎没有被吓到
汤姆不想跟任何人说话
汤姆不想在波士顿工作
湯姆不浪費一點時間，不是麼
汤姆甚至没打算帮玛丽
汤姆没有微波炉
汤姆不知道玛丽住在哪里
湯姆看來不是加拿大人
汤姆一般不吃早饭
汤姆不想谈这件事
湯姆懷疑瑪麗是否誠實
湯姆感覺他心跳加快
汤姆经常说梦话
Tom每天早上去散步
汤姆今早出发晚了
汤姆最近相当忙
Tom最近变得健忘了
汤姆环游了世界
湯姆還沒吃完他的晚飯
湯姆把日曆挂在墙上
湯姆是我的遠亲
汤姆比玛丽年轻许多
汤姆是法语母语者
湯姆總是在玩電視遊樂器
湯姆總是在看電視
汤姆急着想知道结果
湯姆住在波士頓某地
汤姆年纪足够去上学了
汤姆正在自己房间里看书
汤姆正在教我怎么开帆船
汤姆是这个班级里唯一的男生
汤姆正在等

塑料盘子在烤箱里会化的
一个聪明人不会说这种话
代表人工智能
實際上，我沒有建議甚麼
所有美国人都需要缴税
火車上有預訂的座位嗎
你絶對確定這事嗎
你确定这就是你想要的吗
你在做你覺得對的事嗎?
你經常服用任何藥物嗎
没有合格的申请人吗
亚美尼亚语是一门印欧语言
问他会不会来参加会议
十一点准时到车站
波士頓是養小孩的好地方
能再告诉我一点吗
来吧我想让你看点东西
請您再說一遍好嗎
你能告訴我我的選項是甚麼嗎
你聽說了昨天的火災嗎?
你有一本用英文寫的書嗎
你發燒和喉嚨痛嗎?
你有除锈的东西吗
你知道這個意外是如何發生的嗎
请问现在波士顿是几点钟
你知道现在哪本书卖得好吗
你知道这是谁的字吗
你經常早餐喝茶嗎
你想成為一名電影演員嗎
你想跟我去野餐吗
你想知道为什么我对Tom说话吗
這裡有人知道湯姆住在哪裡嗎
我学习的时候不要打扰我
当我学习的时候不要打扰我
列车停下前别下车
上課中不要跟別人講話
不要低估自己的实力
在考试的时候，汤姆作弊抄了玛丽的答案
世界各地都讀英語
再怎麼經驗老到的司機都會出錯
儘管他有那麼多錢，他並不快樂
每个人都知道汤姆的法语很好
每个人都有他的长处和短处
每个人都知道汤姆的法语很好
每個人都應該帶自己的午餐
所有事都取決於你的決定
抱歉，火車站在哪裡
對教師來說，教她很有趣
4在日本是一个不幸的数字
哈雷彗星將在2061回來
你曾经得过重病吗
他求她跟他结婚七次
他把她的秘密告诉了他的朋友
他似乎无法理解那首诗
他給了他的孩子們良好的教育
他一个月剪三次头发
他有权出入美国大使馆
他一直暗恋着她
他是个绝对不会偷工减料的人
他面臨著許多困難
他玩股票赔了
他在那次意外中失去了他的視力
他讓對面的房間都能聽到他的聲音
他盡力地利用了他的機會
他更愿意工作而不是无所事事
他什么也没说，这让她很生气
他在班上出類拔萃
他试图把注意力集中在信上
他对他们的请求置若罔闻
他在心里反复思量这件事
他因为没有被邀请而气得快疯了
他反对种族歧视
海倫凱勒眼盲，耳聾，又啞
这儿是他们通常吃晚饭的地方
他弟弟是个有名的足球选手
他的公司沒有從危機中倖存
他的工作是驾驶观光巴士
他退休後的生活不快樂
他的发音远非完美
他的演讲简短且切中要害
誠實不總是最好的策略
希望我們會喜歡我們的中國之旅
你怎么样旅游愉快吗
你们怎么得出这个结论的
“我爱你”用法语怎么讲

他身肩重任
經過數次延遲之後，飛機終於離開了
吃過午飯後，她準備好要出門了
暴风雨过后，他们的房子成了废墟
农业需要消耗的大量水
酒的消费每年都在上升
所有餅乾都是星星的形狀
所有迹象表明她好起来了
美国妇女没有选举权
你们准备参加会议吗
你确定要自己做这个吗
你可以留在這裡
因为下雪了，我什么也没能看见
在加拿大的人說法語和英語
西藍花是最健康的蔬菜之一
西蘭花是最健康的蔬菜之一
你能帮我把这译成法语吗
你知道这儿附近有什么好餐馆吗?
你参加社团活动吗
医生发现了一些令人吃惊的事实
不要忘记汤姆对花生过敏
各國有不同的飲食習慣
英語和德語是兩種相關的語言
英语成为了一门国际语言
每個人都很欣賞他所畫的圖畫
每个人都知道他对那狗的感情
我錯開了你的信
父親給我買了最新型的摩托車
很少有東西像音樂一樣帶給我們這麼多的快樂
佛罗伦萨是意大利最美丽的城市
食物在吞咽前要经过咀嚼
他從去年二月開始就沒寫信給我們
他和班上其他男生一样聪明
他寻找一切可能的逃生途径
今天早上他收到好多信
他努力学习，为的是能够考上大学
当他听到那个新闻的时候，他感动得哭了
他彈鋼琴，她唱歌
他写了本关于美国南北战争的书
他是营销部的负责人
海明威喜歡在非洲的大狩獵
他弟弟是个有名的足球选手
纽约市的人口有多少
你打算在这个国家待多久
走着去火车站要多久
我承認我不知道怎麼做
我將要在這裡待幾天
目前我待在酒店
我等你把作業做完
我在上商店花低价买了录像机
我不能同時注意两件事
在他倒下前我抓住了他的手臂
我能听见鸟在窗外歌唱
我因為門關著進不去
我无法忍受她傲慢的态度
我不知道是否該同意或拒絕
我今天早上不想散步
我不知道他是否已经为我做好了
我不知道那是不是汤姆想要的
我不知道你不喜欢汤姆的理由
我不太喜欢他，其实我讨厌他
我不记得事故的情况
我不觉得她像她妈妈
我不明白您想说什么
她開朗的個性使我覺得快樂
我必须在礼拜六之前把书还回去
这几天我脑袋里的事情太多了
我刚跟汤姆的一些朋友吃了晚饭
我需要找個地方練舞
我记得我把书还到图书馆了
我昨晚应该早点睡觉的
除了雨天我每天都散步
我认为采用他的计划对我们比较好
我認為我們找到我們正在找的東西了
我以为汤姆今晚有足球比赛
我想特别强调这一点
我想为你今天所做的事感谢你
我因為有你的建議纔能成功
我一回到家就打电话给你
我要明確表示我不會再來

她真的樂瘋了
我们对这次的延迟表示抱歉，并对可能造成的不便表示遗憾
根據報載，有一架飛機昨天晚上發生了意外
他教了兩年的英語
如果一个人有11只羊，除了9只之外，其他全部死了，那么他还剩下几只羊呢
如果那天下雨，比赛会顺延至下一个晴天
给你解释这为什么行不通要花很多时间
该国严禁进口稀有野生动物
忠犬八公的雕像伫立在涩谷站前
汤姆觉得他有机会在股市赚一大笔钱
每一個人對事情的看法不同是依據他們是富有還是貧窮
尽管政府拒绝承认，它的经济政策还是失败了
Mary试图把围裙围在腰上，然后把烤鸡从炉子里拿出来
玛丽把围裙系在她的腰上，然后把火鸡从烤箱里拿出来了
人們看待事情的角度不同取決於他們是富裕或貧窮
倫敦的人口遠遠多於其他英國城市的人口
他们认为，去反驳一个不认识的人有些不礼貌
四分之三的美国人相信存在超自然现象
汤姆得出无论他做什么，玛丽都不会喜欢的结论
全世界百分之八十電腦上的資訊都是用英語寫的
我以为我们发现了绝妙的藏身之处，但警察找到了我们
早上起来，嗓子变得很沙哑，我想是不是感冒了
如果看起来像个苹果而且吃起来也像苹果的话，可能就是苹果
世界就像是一本书，走一步等于翻了一页
今天，我本打算在图书馆学习但到12点左右才醒
Tom写作可以写的像本国人一样，可是他的发音很烂
汤姆尽了全力，但他还是不能获得比玛丽更高的等级
当列车停止时，所有的乘客都想知道发生了什么
Lindbergh於1927年成功完成了第一次獨自飛越大西洋
他的分数总比我高，尽管他学习得少一点
其实我工作并不多，但足以让我这周在办公室里忙着了
我还了从图书馆借的书，又借了些新的
文章的发表被预定在教授生日那天
她受歡迎不是因為她的美麗，而是因為她親切地對待每個人
电话运营商提示来电人等候接通
那些说钱不能买来幸福的人，只是不知道上哪里去买而已
當時沒有任何以英語為母語的人在公立學校任教
如果你远离危险区域，里约热内卢就是完全安全的
她被要求去说服他以让他或者他的儿子或者是别的人来粉刷屋子
汤姆总是说话声音太小，我几乎听不懂他在说什么
尽管我在学校学了6年英语，我还是说不好
我不知道这个城市，而且我一点都不懂那里的语言
两个孩子的年龄加起来和他们的父亲相当
对工具箱里只有一把榔头的人来说，所有的问题都像钉子
汤姆去河里游泳，但当他出来时，他的衣服被偷了
作為一個良好的交談者，並不只意味著作一個英語

In [4]:
enlish =  enl
chines = chi

In [5]:
tokenizer_en = tfds.features.text.SubwordTextEncoder.build_from_corpus(( e for e in enlish), target_vocab_size=2**13)

KeyboardInterrupt: 

In [6]:
tokenizer_cn = tfds.features.text.SubwordTextEncoder.build_from_corpus((' '.join(e) for e in chines), target_vocab_size=2**13)

In [6]:
tokenizer_cn.save_to_file('./cn_word')
tokenizer_en.save_to_file('./en_word')

NameError: name 'tokenizer_cn' is not defined

In [7]:
tokenizer_en = tfds.features.text.SubwordTextEncoder.load_from_file('./en_word')
tokenizer_cn = tfds.features.text.SubwordTextEncoder.load_from_file('./cn_word')

In [24]:
print(tokenizer_en.decode([1,2728]))
print(tokenizer_cn.decode([147 , 560 ,  11]))

I laughed
我笑了


In [9]:
cn = [tokenizer_cn.encode(line)for line in chines]

In [10]:
en= [tokenizer_en.encode(line)for line in enlish]

In [11]:
en_ = []
for i in en :
    en_.append([tokenizer_en.vocab_size]+list(i)+[tokenizer_en.vocab_size+1])
cn_ = []
for i in cn :
    cn_.append([tokenizer_cn.vocab_size]+list(i)+[tokenizer_cn.vocab_size+1])

In [12]:
en_text=tf.keras.preprocessing.sequence.pad_sequences(
    en_, maxlen=40, dtype='int32', padding='post',
    value=0.0)
cn_text=tf.keras.preprocessing.sequence.pad_sequences(
    cn_, maxlen=40, dtype='int32', padding='post',
    value=0.0)

In [14]:
en_text[1]

array([6466, 1813, 6467,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0])

In [15]:
cn_text[1]

array([5339,  111,  115, 5340,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0])

In [16]:

en_batch = tf.data.Dataset.from_tensor_slices(en_text)
cn_batch = tf.data.Dataset.from_tensor_slices(cn_text)

In [17]:
en_batch  = en_batch.padded_batch(64)
cn_batch = cn_batch.padded_batch(64)

In [18]:
x=next(iter(en_batch ))
print(x.shape)
print(x)

(64, 40)
tf.Tensor(
[[6466 1813 6467 ...    0    0    0]
 [6466 1813 6467 ...    0    0    0]
 [6466 6065 6467 ...    0    0    0]
 ...
 [6466 6077 2431 ...    0    0    0]
 [6466 1055   35 ...    0    0    0]
 [6466 2224  208 ...    0    0    0]], shape=(64, 40), dtype=int32)


In [22]:
data = zip(en_batch,cn_batch)

In [23]:
de_batch, en_batch = next(iter(data))

In [24]:
print(de_batch[1])
print(en_batch[1])

tf.Tensor(3240, shape=(), dtype=int32)
tf.Tensor(
[5339  111  115 5340    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0], shape=(40,), dtype=int32)


In [15]:
import tensorflow.keras
import tensorflow_datasets as tfds
import tensorflow as tf
y_true = [[2],[1]]
y_pred = [[0.1，0.9，0.8]，[0.05，0.95，0]]
m = tf.keras.metrics.sparse_categorical_accuracy（y_true，y_pred）

SyntaxError: invalid character in identifier (<ipython-input-15-e592926bf99e>, line 5)

In [12]:
y_true = [2,2] 
y_pred = [[0.1，0.9，0.8]，[0.05，0.95，0]]
m = tf.keras.metrics.sparse_categorical_accuracy（y_true，y_pred）

SyntaxError: invalid character in identifier (<ipython-input-12-3f858cdb497a>, line 2)

In [14]:
tar_real= [[2], [1]] 
predictions = [[0.1, 0.3, 0.6], [0.05, 0.95, 0]]

In [15]:
import tensorflow as tf
import tensorflow.keras.layers as layers
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')
train_accuracy(tar_real, predictions)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [16]:
print(train_accuracy.result())

tf.Tensor(1.0, shape=(), dtype=float32)
